<?php


	?>

	<div class="container-fluid">

		<?php /*var_dump($postsDroite, $postsCentre)*/     ?>

		<?php if (count($postsGauche) > 0) : ?>
			<h4> Position du Communiqué Gauche</h4>
			<table>
				<caption>Articles</caption>
				<thead>
					<tr>
						<th>Titre</th>
						<th>Date de publication</th>
						<th colspan="2">Actions</th>
					</tr>
				</thead>

				<tbody>
					<?php foreach ($postsGauche as $post) : ?>
						<tr>
							<td><?= htmlspecialchars($post['title']) ?></td>
							<td><?= $post['publicationDate'] ?></td>
							<td>
								<a href="../controller/edit-post.php?id=<?= intval($post['id']) ?>" class="btn btn-primary">Modifier</a>
							</td>
							</br>
							<td>
								<a href="../controller/delete-post.php?id=<?= intval($post['id']) ?>" class="btn btn-danger">Supprimer</a>
							</td>

						</tr>

					<?php endforeach; ?>
				</tbody>
			</table>


		<?php endif; ?>
		<a href="../controller/write-post.php" class="btn btn-success">Rédiger un article</a>


		</br></br></br>



		<?php if (count($postsCentre) > 0) : ?>

			<table>
				<caption>Articles</caption>
				<h4> Position des Communiqués Centre</h4>
				<thead>
					<tr>
						<th>Titre</th>
						<th>Date de publication</th>
						<th colspan="2">Actions</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($postsCentre as $post) : ?>
						<tr>
							<td><?= htmlspecialchars($post['title']) ?></td>
							<td><?= $post['publicationDate'] ?></td>
							<td>
								<a href="../controller/edit-post.php?id=<?= intval($post['id']) ?>" class="btn btn-primary">Modifier</a>
							</td>
							</br>
							<td>
								<a href="../controller/delete-post.php?id=<?= intval($post['id']) ?>" class="btn btn-danger">Supprimer</a>
							</td>

						</tr>
					<?php endforeach; ?>
				</tbody>
			</table>

		<?php endif; ?>

		<a href="../controller/write-post.php" class="btn btn-success">Rédiger un article</a>


		</br></br></br>
		<?php if (count($postsDroite) > 0) : ?>
			<h4> Position du Communiqué Gauche</h4>
			<table>
				<caption>Articles</caption>
				<thead>
					<tr>
						<th>Titre</th>
						<th>Date de publication</th>
						<th colspan="2">Actions</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($postsDroite as $post) : ?>
						<tr>
							<td><?= htmlspecialchars($post['title']) ?></td>
							<td><?= $post['publicationDate'] ?></td>
							<td>
								<a href="../controller/edit-post.php?id=<?= intval($post['id']) ?>" class="btn btn-primary">Modifier</a>
							</td>
							</br>
							<td>
								<a href="../controller/delete-post.php?id=<?= intval($post['id']) ?>" class="btn btn-danger">Supprimer</a>
							</td>

						</tr>
					<?php endforeach; ?>
				</tbody>
			</table>


		<?php endif; ?>


		<a href="../controller/write-post.php" class="btn btn-success">Rédiger un article</a>


		</br></br></br>

		<?php if (count($content) > 0) : ?>

			<table>
				</br></br> </br></br>
				<caption>Commentaires</caption>
				<thead>
					<tr>
						<th>Titre</th>
						<th>Date de publication</th>
						<th colspan="2">Actions</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($comments as $comment) : ?>
						<tr>
							<td><?= htmlspecialchars($comment['title']) ?></td>
							<td><?= $comment['publicationDate'] ?></td>
							<td>
								<a href="../controller/<?= intval($post['id']) ?>" class="btn btn-primary"> Valider </a>
							</td>
							<td>
								<a href="../controller/<?= intval($post['id']) ?>" class="btn btn-danger"> Supprimer </a>
							</td>
						</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		<?php endif; ?>
	</div>