<!DOCTYPE html>
<html lang="fr">

<head>
	<meta charset="utf-8">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<title>Blog : Tableau de bord</title>
</head>

<body>
	<?php require '../views/navigation.phtml' ?>

	<div class="pos-f-t">
		<div class="collapse" id="navbarToggleExternalContent">
			<div class="bg-dark p-4">
				<h4 class="text-white">Accueil administrateur</h4>
				<span class="text-muted"></span>
			</div>
		</div>
		<nav class="navbar navbar-dark bg-dark">
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
		</nav>
	</div>


	<br><br><br><br>

	<?php $msg = '';
			if (isset($_POST['upload'])) {
				$image = $_FILES['image']['name'];
				$path = 'img/' . $image;

				if ($req) {
					//utiliser la fonction
					move_uploaded_file($_FILES['image']['tmp_name'], $path);
					$msg = 'l"image a été chargée avec succés!';
				} else {
					$msg = 'Echec du chargement de l"image!';
				}
			}
			?>
	<div class="row justify-content-center">

		<div class="col-lg-4 bg-dark rounded px-4">
			<h3 class="text-center text-light p-1"> Selectionner une image pour votre carousel </h3>
			<form action="index.php" method="post" enctype="multipart/form-data">
				<div class="form-group">
					<input type="file" name="image" class="form-control p-1" required>
				</div>
				<div class="class-form-group">
					<input type="submit" name="upload" class="btn btn-warning btn-block" value="Upload Image">
				</div>
				<div class="form-group">
					<h5 class="text-center text-light"><?= $msg; ?></h5>
				</div>
			</form>

		</div>
	</div>
	<br><br><br><br>

	<div class="container-fluid">

	<?php /*var_dump($postsDroite, $postsCentre)*/     ?>

		<?php if (count($postsGauche) > 0) : ?>
			<h4> Position du Communiqué Gauche</h4>
			<table>
				<caption>Articles</caption>
				<thead>
					<tr>
						<th>Titre</th>
						<th>Date de publication</th>
						<th colspan="2">Actions</th>
					</tr>
				</thead>
				
				<tbody>
					<?php foreach ($postsGauche as $post) : ?>
						<tr>
							<td><?= htmlspecialchars($post['title']) ?></td>
							<td><?= $post['publicationDate'] ?></td>
							<td>
								<a href="../controller/edit-post.php?id=<?= intval($post['id']) ?>" class="btn btn-primary">Modifier</a>
							</td>
							</br>
							<td>
								<a href="../controller/delete-post.php?id=<?= intval($post['id']) ?>" class="btn btn-danger">Supprimer</a>
							</td>

						</tr>
						
					<?php endforeach; ?>
				</tbody>
			</table>


		<?php endif; ?>
		<a href="../controller/write-post.php" class="btn btn-success">Rédiger un article</a>


		</br></br></br>



		<?php if (count($postsCentre) > 0) : ?>

<table>
	<caption>Articles</caption>
	<h4> Position des Communiqués Centre</h4>
	<thead>
		<tr>
			<th>Titre</th>
			<th>Date de publication</th>
			<th colspan="2">Actions</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($postsCentre as $post) : ?>
			<tr>
				<td><?= htmlspecialchars($post['title']) ?></td>
				<td><?= $post['publicationDate'] ?></td>
				<td>
					<a href="../controller/edit-post.php?id=<?= intval($post['id']) ?>" class="btn btn-primary">Modifier</a>
				</td>
				</br>
				<td>
					<a href="../controller/delete-post.php?id=<?= intval($post['id']) ?>" class="btn btn-danger">Supprimer</a>
				</td>

			</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<?php endif; ?>

<a href="../controller/write-post.php" class="btn btn-success">Rédiger un article</a>


		</br></br></br>
<?php if (count($postsDroite) > 0) : ?>
<h4> Position du Communiqué Gauche</h4>
<table>
	<caption>Articles</caption>
	<thead>
		<tr>
			<th>Titre</th>
			<th>Date de publication</th>
			<th colspan="2">Actions</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($postsDroite as $post) : ?>
			<tr>
				<td><?= htmlspecialchars($post['title']) ?></td>
				<td><?= $post['publicationDate'] ?></td>
				<td>
					<a href="../controller/edit-post.php?id=<?= intval($post['id']) ?>" class="btn btn-primary">Modifier</a>
				</td>
				</br>
				<td>
					<a href="../controller/delete-post.php?id=<?= intval($post['id']) ?>" class="btn btn-danger">Supprimer</a>
				</td>

			</tr>
		<?php endforeach; ?>
	</tbody>
</table>


<?php endif; ?>


		<a href="../controller/write-post.php" class="btn btn-success">Rédiger un article</a>


		</br></br></br>

		<?php if (count($content) > 0) : ?>

			<table>
				</br></br> </br></br>
				<caption>Commentaires</caption>
				<thead>
					<tr>
						<th>Titre</th>
						<th>Date de publication</th>
						<th colspan="2">Actions</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($comments as $comment) : ?>
						<tr>
							<td><?= htmlspecialchars($comment['title']) ?></td>
							<td><?= $comment['publicationDate'] ?></td>
							<td>
								<a href="../controller/<?= intval($post['id']) ?>" class="btn btn-primary"> Valider </a>
							</td>
							<td>
								<a href="../controller/<?= intval($post['id']) ?>" class="btn btn-danger"> Supprimer </a>
							</td>
						</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		<?php endif; ?>
	</div>
</body>

</html>