<html lang="fr">
	<head>
		<meta charset="utf-8">
		<title>Blog : Rédaction d'un article</title>
	</head>
	<body>
		<?php require '../views/navigation.phtml' ?>
		<h1>Modification d'un article</h1>
		<form action="edit-post.php" method="post" enctype="multipart/form-data">
			<input type="text" name="title" placeholder="Titre" required>
			<textarea name="content" placeholder="Contenu" required></textarea>
			<input type="hidden" name="MAX_FILE_SIZE" value="3000000">
			<input type="file" name="image" accept="image/png, image/jpeg">
			<button type="submit">Enregistrer la modification</button>
		</form>
	</body>
</html>
