<!DOCTYPE html>
<html lang="fr">

<head>
<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="../css/index.css">
	<link
      rel="stylesheet" media="only screen and (max-width:700px)"
      href="../css/index.mobile.css">
	<!-- <link
      href="https://fonts.googleapis.com/css?family=Long+Cang|Montserrat:300,400,700&display=swap"
      rel="stylesheet"
    /> -->
	<script
      src="https://kit.fontawesome.com/83f4286022.js"
      crossorigin="anonymous"
    ></script>
    <link
      href="https://fonts.googleapis.com/css?family=Cormorant+Garamond|Staatliches&display=swap"
      rel="stylesheet"
    />
	<title>Blog : Tous les articles</title>
</head>

<body>
	<?php require '../views/navigation.phtml' ?>
	
	<!-- <h1>Tous les articles</h1> -->

	<section class="showcase">
	
        <article>
		<?php foreach ($posts as $post) : ?>
		<a href="../controller/post.php?id=<?= intval($post['id']) ?>">
		<?php if (!is_null($post['imageFileName'])) : ?>
			<img src="../uploads/<?= htmlspecialchars($post['imageFileName']) ?>" alt="<?= htmlspecialchars($post['title']) ?>">
		<?php endif; ?>
		  <h3><?= htmlspecialchars($post['title']) ?></h3>
         
		  <p>Rédigé par <a href="../controller/writer.php?id=<?= intval($post['writerId']) ?>">
				<?= htmlspecialchars($post['writerUsername']) ?></a></br>Lire la suite</p>
				<p class="text-hint">le <?= $post['publicationDate'] ?>
				
				<i class="fas fa-star mx-1"></i>
		</p>
         
		  <?php endforeach ?>
        </article>
	


		<article class="article-small">
        <?php foreach ($posts as $post) : ?>
		<a href="../controller/post.php?id=<?= intval($post['id']) ?>">
		<?php if (!is_null($post['imageFileName'])) : ?>
			<img src="../uploads/<?= htmlspecialchars($post['imageFileName']) ?>" alt="<?= htmlspecialchars($post['title']) ?>">
		<?php endif; ?>
		  <h3><?= htmlspecialchars($post['title']) ?></h3>
       
		  <p>Rédigé par <a href="../controller/writer.php?id=<?= intval($post['writerId']) ?>">
				<?= htmlspecialchars($post['writerUsername']) ?></a></br>Lire la suite</p>
				<p class="text-hint">le <?= $post['publicationDate'] ?>
				<i class="fas fa-star mx-1"></i>
		</p>
          
		  <?php endforeach ?>
        </article>


		<article class="article-small">
        <?php foreach ($posts as $post) : ?>
		<a href="../controller/post.php?id=<?= intval($post['id']) ?>">
		<?php if (!is_null($post['imageFileName'])) : ?>
			<img src="../uploads/<?= htmlspecialchars($post['imageFileName']) ?>" alt="<?= htmlspecialchars($post['title']) ?>">
		<?php endif; ?>
		  <h3><?= htmlspecialchars($post['title']) ?></h3>
         
		  <p>Rédigé par <a href="../controller/writer.php?id=<?= intval($post['writerId']) ?>">
				<?= htmlspecialchars($post['writerUsername']) ?></a></br>Lire la suite</p>
				<p class="text-hint">le <?= $post['publicationDate'] ?>
				<i class="fas fa-star mx-1"></i>
		</p>
         
		  <?php endforeach ?>
        </article>

		

		<article>
		<?php foreach ($posts as $post) : ?>
		<a href="../controller/post.php?id=<?= intval($post['id']) ?>">
		<?php if (!is_null($post['imageFileName'])) : ?>
			<img src="../uploads/<?= htmlspecialchars($post['imageFileName']) ?>" alt="<?= htmlspecialchars($post['title']) ?>">
		<?php endif; ?>
		  <h3><?= htmlspecialchars($post['title']) ?></h3>
        
		  <p>Rédigé par <a href="../controller/writer.php?id=<?= intval($post['writerId']) ?>">
				<?= htmlspecialchars($post['writerUsername']) ?></a></br>Lire la suite</p>
				<p class="text-hint">le <?= $post['publicationDate'] ?>
				<i class="fas fa-star mx-1"></i>
		</p>
          
		  <?php endforeach ?>
        </article>
	</section>

		<section class="ads">
        <img src="img/ads.png" alt="ads" />
        <h1>Lorem ipsum dolor, sit amet consectetur</h1>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptas,
          doloremque?
        </p>
        <form action="#">
          <input placeholder="Adresse Email" type="text" />
          <button class="btn btn-dark">Inscription</button>
        </form>
      </section>



      <section class="content">
        <div class="articles">
          <h2 class="underline">Communiqués</h2>
          <article>

		  <?php foreach ($posts as $post) : ?>
		<a href="../controller/post.php?id=<?= intval($post['id']) ?>">
			<h3 class="underline"><?= htmlspecialchars($post['title']) ?></h3>
		</a>

		<?php if (!is_null($post['imageFileName'])) : ?>
			<img src="../uploads/<?= htmlspecialchars($post['imageFileName']) ?>" alt="<?= htmlspecialchars($post['title']) ?>">
		<?php endif; ?>
		<p class="article-author" class="text-hint">Rédigé par <a href="../controller/writer.php?id=<?= intval($post['writerId']) ?>">
				<?= htmlspecialchars($post['writerUsername']) ?></a></br>Lire la suite</p>
				<p class="text-hint"> le <?= $post['publicationDate'] ?>
				<i class="fas fa-star mx-1"></i>
		</p>
          
			<?php endforeach ?>
          </article>
		</div>

		<div class="popular">
          <h2 class="underline">Populaires</h2>
          <ul>
            <li>
              <div>01</div>
              <div>
			  <?php foreach ($posts as $post) : ?>
				<a href="../controller/post.php?id=<?= intval($post['id']) ?>">
			<h3><?= htmlspecialchars($post['title']) ?></h3>
		        </a>
				<?php if (!is_null($post['imageFileName'])) : ?>
			<img src="../uploads/<?= htmlspecialchars($post['imageFileName']) ?>" alt="<?= htmlspecialchars($post['title']) ?>">
		<?php endif; ?>
                <p class="article-author">
				Rédigé par <a href="../controller/writer.php?id=<?= intval($post['writerId']) ?>">
				<?= htmlspecialchars($post['writerUsername']) ?></a></br>Lire la suite</p>
				<p class="text-hint">le <?= $post['publicationDate'] ?>
				<i class="fas fa-star mx-1"></i>
                </p>
				<?php endforeach ?>
              </div>
            </li>


		


			



            <li>
              <div>02</div>
              <div>
                <h3>Lorem ipsum dolor sit amet.</h3>
                <p class="article-author">Lorem, ipsum</p>
                <p class="text-hint">
                  Oct 26 - 2 min read <i class="fas fa-star mx-1"></i>
                </p>
              </div>
            </li>
            <li>
              <div>03</div>
              <div>
                <h3>Lorem ipsum dolor sit amet.</h3>
                <p class="article-author">Lorem, ipsum</p>
                <p class="text-hint">
                  Oct 26 - 2 min read <i class="fas fa-star mx-1"></i>
                </p>
              </div>
            </li>
            <li>
              <div>04</div>
              <div>
                <h3>Lorem ipsum dolor sit amet.</h3>
                <p class="article-author">Lorem, ipsum</p>
                <p class="text-hint">
                  Oct 26 - 2 min read <i class="fas fa-star mx-1"></i>
                </p>
              </div>
            </li>
          </ul>
        </div>
	</section>
</body>
</html>
