<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="../css/header.css">
	<link
      rel="stylesheet" media="only screen and (max-width:500px)"
      href="../css/header.mobile.css">
	<link
      href="https://fonts.googleapis.com/css?family=Long+Cang|Montserrat:300,400,700&display=swap"
      rel="stylesheet"
    />
	<title>Document</title>
</head>

<body>
	<div class="vp-container">
		<header>
			<h2 class="vp-logo">
				<img src="../img/logo.jpg" alt="" title="logo" style="height:65px">
				<a href="#">Service de presse</a>
				</h2>
				
				<?php if (!array_key_exists('userId', $_SESSION)) : ?>
					<ul>
					<li><a href="./">Accueil</a></li>
				    <!-- <li><a href="../controller/sign-up.php">Inscription</a></li> -->
					<li><a href="../controller/sign-in.php" button class="btn btn-light">Connexion</button></a></li>
					
					</ul>
				<?php else : ?>
					<ul>
					<li><a href="../controller/dashboard.php">Tableau de bord</a></li>
					<li><a href="../controller/sign-out.php">Déconnexion</a></li>
					</ul>
					<?php endif; ?>
		
		</header>
	</div>

</body>

</html>