<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<title>Blog : Inscription</title>
	</head>
	<body>
		<?php require '../views/navigation.phtml' ?>
		<h1>Inscription</h1>
		<form action="../views/sign-up.php" method="post">
			<input type="text" name="username" placeholder="Nom d'utilisateur" required autocomplete="off">
			<input type="password" name="password" placeholder="Mot de passe" required>
			<button type="submit">S'inscrire</button>
		</form>
	</body>
</html>
