<!DOCTYPE html>
<html lang="fr">

<head>
	<meta charset="utf-8">
	<title>Blog : Identification</title>
	<link rel="stylesheet" href="../css/inscription.css">
</head>

<body>

	




	<div class="login-page">
		<div class="form">
			<form action="../controller/sign-in.php" method="post">
				<input type="email" name="email" placeholder="Nom d'utilisateur" required autocomplete="off">
				<input type="password" name="password" placeholder="Mot de passe" required>
				<button type="submit">Connexion</button>
			</form>
		</div>
	</div>

	
</body>

</html>